# Generated by Django 3.2 on 2022-12-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz_pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
    ]
